In [28]:
import torch
d_model = 10
beg = 0
end = 4
freq_seq = torch.arange(0, d_model, 2.0)
inv_freq = 1 / (10000 ** (freq_seq / d_model))
fwd_pos_seq = torch.arange(beg, end, 1.0)

sinusoid_inp = torch.einsum('i,d->id', fwd_pos_seq, inv_freq)
forward_pos_emb = torch.cat([torch.sin(sinusoid_inp), torch.cos(sinusoid_inp)], dim=-1)
pos_emb = pos_emb[:, :]

In [23]:
import pandas as pd

import numpy as np

In [33]:
freq_seq

tensor([0., 2., 4., 6., 8.])

In [34]:
inv_freq

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])

In [36]:
fwd_pos_seq

tensor([0., 1., 2., 3.])

In [35]:
sinusoid_inp

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04],
        [2.0000e+00, 3.1698e-01, 5.0238e-02, 7.9621e-03, 1.2619e-03],
        [3.0000e+00, 4.7547e-01, 7.5357e-02, 1.1943e-02, 1.8929e-03]])

In [30]:
val = np.array(forward_pos_emb)
zz = pd.DataFrame(val)

In [32]:
zz

0         1         2         3         4         5         6  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000  1.000000   
1  0.841471  0.157827  0.025116  0.003981  0.000631  0.540302  0.987467   
2  0.909297  0.311697  0.050217  0.007962  0.001262 -0.416147  0.950181   
3  0.141120  0.457755  0.075285  0.011943  0.001893 -0.989992  0.889079   

          7         8         9  
0  1.000000  1.000000  1.000000  
1  0.999685  0.999992  1.000000  
2  0.998738  0.999968  0.999999  
3  0.997162  0.999929  0.999998

In [ ]:
zz['v'] = val

In [15]:
pd.DataFrame(np.array(pos_emb.tolist()))

ValueError: Must pass 2-d input